name = "Factions Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07b14712032a52499d569b4c88c7beb852a47656802bb84b72d4323806c870f2"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"

[options]
acceptable-game-versions = ["1.19.2", "1.19"]
