name = "Factions Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79829487b5e757537ac8c5695cafbdff7e4fecf3e2156f9e93baae1104ac18f7"

[versions]
minecraft = "1.19.2"
quilt = "0.17.11"

[options]
acceptable-game-versions = ["1.19.2", "1.19"]
