name = "Factions Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "032df248c7b2d39b745b483a83c7bb24451b90e417e15639b58ab2dcc27d0260"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"

[options]
acceptable-game-versions = ["1.19.2", "1.19"]
