name = "Factions Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad400264498be4804f9ee0d8d936a1fa881cb89ae5a2c1a5524590aa4b906102"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"

[options]
acceptable-game-versions = ["1.19.2", "1.19"]
