name = "Factions Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bf6fb050596fd3e73269efbf3f7948d41f7381e0025882c090726a7cb2152f0"

[versions]
minecraft = "1.19.2"
quilt = "0.17.11"

[options]
acceptable-game-versions = ["1.19.2", "1.19"]
