name = "Factions Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c18cd116a02a59cc2c8e7111a095c198641d7d285c334063d4c43955f3638c4"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"

[options]
acceptable-game-versions = ["1.19.2", "1.19"]
