name = "Factions Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f555dc3441ab771fb4a96da7e481b7e42901b7e158672d03c5e38855c9f6fd2b"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"

[options]
acceptable-game-versions = ["1.19.2", "1.19"]
