
[registry_sync]
	# Message displayed for players joining with incompatible clients. Support strings and Minecraft's JSON text format.
	# default: Unsupported (vanilla?) client!
	#This server requires a modded client to join!
	missing_registry_sync_message = '["Unsupported client!\nThis server requires the latest version of the ",{"text":"Factions Pack","underlined":true,"clickEvent":{"action":"open_url","value":"https://github.com/ryleu/factions-pack"}},".\nIf you already have this installed, please restart your client."]'
	# Allows players with Fabric API to connect, as long as they have all required mods.
	# default: true
	support_fabric_api_protocol = false

